-- create some suburbs
INSERT INTO suburb (suburb) VALUES('Auckland City');
INSERT INTO suburb (suburb) VALUES('CBD');
INSERT INTO suburb (suburb) VALUES('East');
INSERT INTO suburb (suburb) VALUES('West');
INSERT INTO suburb (suburb) VALUES('Arch Hill');
INSERT INTO suburb (suburb) VALUES('Avondale');
INSERT INTO suburb (suburb) VALUES('Blockhouse Bay');
INSERT INTO suburb (suburb) VALUES('Balmoral');
INSERT INTO suburb (suburb) VALUES('Eden Terrace');
INSERT INTO suburb (suburb) VALUES('Eden Valley');
INSERT INTO suburb (suburb) VALUES('Ellerslie');
INSERT INTO suburb (suburb) VALUES('Epsom');
INSERT INTO suburb (suburb) VALUES('Freemans Bay');
INSERT INTO suburb (suburb) VALUES('Glendowie');
INSERT INTO suburb (suburb) VALUES('Glen Innes');
INSERT INTO suburb (suburb) VALUES('Grafton');
INSERT INTO suburb (suburb) VALUES('Greenlane');
INSERT INTO suburb (suburb) VALUES('Greenwoods Corner');
INSERT INTO suburb (suburb) VALUES('Grey Lynn');
INSERT INTO suburb (suburb) VALUES('Herne Bay');
INSERT INTO suburb (suburb) VALUES('Hillsborough');
INSERT INTO suburb (suburb) VALUES('Kingsland');
INSERT INTO suburb (suburb) VALUES('Kohimarama');
INSERT INTO suburb (suburb) VALUES('Lynfield');
INSERT INTO suburb (suburb) VALUES('Meadowbank');
INSERT INTO suburb (suburb) VALUES('Mission Bay');
INSERT INTO suburb (suburb) VALUES('Morningside');
INSERT INTO suburb (suburb) VALUES('Mount Albert');
INSERT INTO suburb (suburb) VALUES('Mount Eden');
INSERT INTO suburb (suburb) VALUES('Mount Roskill');
INSERT INTO suburb (suburb) VALUES('Mount Wellington');
INSERT INTO suburb (suburb) VALUES('Newmarket');
INSERT INTO suburb (suburb) VALUES('Newton');
INSERT INTO suburb (suburb) VALUES('New Windsor');
INSERT INTO suburb (suburb) VALUES('Onehunga');
INSERT INTO suburb (suburb) VALUES('One Tree Hill');
INSERT INTO suburb (suburb) VALUES('Orakei');
INSERT INTO suburb (suburb) VALUES('Oranga');
INSERT INTO suburb (suburb) VALUES('Otahuhu');
INSERT INTO suburb (suburb) VALUES('Owairaka');
INSERT INTO suburb (suburb) VALUES('Panmure');
INSERT INTO suburb (suburb) VALUES('Parnell');
INSERT INTO suburb (suburb) VALUES('Penrose');
INSERT INTO suburb (suburb) VALUES('Point England');
INSERT INTO suburb (suburb) VALUES('Point Chevalier');
INSERT INTO suburb (suburb) VALUES('Ponsonby');
INSERT INTO suburb (suburb) VALUES('Remuera');
INSERT INTO suburb (suburb) VALUES('Royal Oak');
INSERT INTO suburb (suburb) VALUES('Saint Heliers');
INSERT INTO suburb (suburb) VALUES('Saint Johns');
INSERT INTO suburb (suburb) VALUES('Saint Marys Bay');
INSERT INTO suburb (suburb) VALUES('Sandringham');
INSERT INTO suburb (suburb) VALUES('Stonefields');
INSERT INTO suburb (suburb) VALUES('Tamaki');
INSERT INTO suburb (suburb) VALUES('Te Papapa');
INSERT INTO suburb (suburb) VALUES('Three Kings');
INSERT INTO suburb (suburb) VALUES('Waikowhai');
INSERT INTO suburb (suburb) VALUES('Waterview');
INSERT INTO suburb (suburb) VALUES('Western Springs');
INSERT INTO suburb (suburb) VALUES('Westfield');
INSERT INTO suburb (suburb) VALUES('Westmere');
INSERT INTO suburb (suburb) VALUES('North Shore');
INSERT INTO suburb (suburb) VALUES('Albany');
INSERT INTO suburb (suburb) VALUES('Bayswater');
INSERT INTO suburb (suburb) VALUES('Bayview');
INSERT INTO suburb (suburb) VALUES('Beach Haven');
INSERT INTO suburb (suburb) VALUES('Belmont');
INSERT INTO suburb (suburb) VALUES('Birkdale');
INSERT INTO suburb (suburb) VALUES('Birkenhead');
INSERT INTO suburb (suburb) VALUES('Browns Bay');
INSERT INTO suburb (suburb) VALUES('Campbells Bay');
INSERT INTO suburb (suburb) VALUES('Castor Bay');
INSERT INTO suburb (suburb) VALUES('Chatswood');
INSERT INTO suburb (suburb) VALUES('Cheltenham');
INSERT INTO suburb (suburb) VALUES('Coatesville');
INSERT INTO suburb (suburb) VALUES('Crown Hill');
INSERT INTO suburb (suburb) VALUES('Cuthill');
INSERT INTO suburb (suburb) VALUES('Devonport');
INSERT INTO suburb (suburb) VALUES('Fairview');
INSERT INTO suburb (suburb) VALUES('Forrest Hill');
INSERT INTO suburb (suburb) VALUES('Glenfield');
INSERT INTO suburb (suburb) VALUES('Glenvar');
INSERT INTO suburb (suburb) VALUES('Greenhithe');
INSERT INTO suburb (suburb) VALUES('Highbury');
INSERT INTO suburb (suburb) VALUES('Hillcrest');
INSERT INTO suburb (suburb) VALUES('Long Bay');
INSERT INTO suburb (suburb) VALUES('Mairangi Bay');
INSERT INTO suburb (suburb) VALUES('Marlborough');
INSERT INTO suburb (suburb) VALUES('Meadowood');
INSERT INTO suburb (suburb) VALUES('Milford');
INSERT INTO suburb (suburb) VALUES('Murrays Bay');
INSERT INTO suburb (suburb) VALUES('Northcote');
INSERT INTO suburb (suburb) VALUES('Northcote Central');
INSERT INTO suburb (suburb) VALUES('Northcote Point');
INSERT INTO suburb (suburb) VALUES('North Harbour');
INSERT INTO suburb (suburb) VALUES('Northcross');
INSERT INTO suburb (suburb) VALUES('Rosedale');
INSERT INTO suburb (suburb) VALUES('Rothesay Bay');
INSERT INTO suburb (suburb) VALUES('Oteha');
INSERT INTO suburb (suburb) VALUES('Pinehill');
INSERT INTO suburb (suburb) VALUES('Stanley Bay');
INSERT INTO suburb (suburb) VALUES('Stanley Point');
INSERT INTO suburb (suburb) VALUES('Sunnynook');
INSERT INTO suburb (suburb) VALUES('Takapuna');
INSERT INTO suburb (suburb) VALUES('Torbay');
INSERT INTO suburb (suburb) VALUES('Totara Vale');
INSERT INTO suburb (suburb) VALUES('Waiake');
INSERT INTO suburb (suburb) VALUES('Wairau Valley');
INSERT INTO suburb (suburb) VALUES('Westlake');
INSERT INTO suburb (suburb) VALUES('Windsor Park');
INSERT INTO suburb (suburb) VALUES('Unsworth Heights');
INSERT INTO suburb (suburb) VALUES('Manukau City');
INSERT INTO suburb (suburb) VALUES('Airport Oaks');
INSERT INTO suburb (suburb) VALUES('Beachlands');
INSERT INTO suburb (suburb) VALUES('Brookby');
INSERT INTO suburb (suburb) VALUES('Bucklands Beach');
INSERT INTO suburb (suburb) VALUES('Chapel Downs');
INSERT INTO suburb (suburb) VALUES('Clendon');
INSERT INTO suburb (suburb) VALUES('Clevedon');
INSERT INTO suburb (suburb) VALUES('Clover Park');
INSERT INTO suburb (suburb) VALUES('Cockle Bay');
INSERT INTO suburb (suburb) VALUES('Dannemora');
INSERT INTO suburb (suburb) VALUES('East Tamaki');
INSERT INTO suburb (suburb) VALUES('Eastern Beach');
INSERT INTO suburb (suburb) VALUES('Farm Cove');
INSERT INTO suburb (suburb) VALUES('Flamboro Heights');
INSERT INTO suburb (suburb) VALUES('Flat Bush');
INSERT INTO suburb (suburb) VALUES('Golflands');
INSERT INTO suburb (suburb) VALUES('Goodwood Heights');
INSERT INTO suburb (suburb) VALUES('Greenmeadows');
INSERT INTO suburb (suburb) VALUES('Half Moon Bay');
INSERT INTO suburb (suburb) VALUES('Heron Point');
INSERT INTO suburb (suburb) VALUES('Highland Park');
INSERT INTO suburb (suburb) VALUES('Hill Park');
INSERT INTO suburb (suburb) VALUES('Howick');
INSERT INTO suburb (suburb) VALUES('Mahia Park');
INSERT INTO suburb (suburb) VALUES('Mangere');
INSERT INTO suburb (suburb) VALUES('Mangere Bridge');
INSERT INTO suburb (suburb) VALUES('Mangere East');
INSERT INTO suburb (suburb) VALUES('Manukau');
INSERT INTO suburb (suburb) VALUES('Manukau Heights');
INSERT INTO suburb (suburb) VALUES('Manurewa');
INSERT INTO suburb (suburb) VALUES('Maraetai');
INSERT INTO suburb (suburb) VALUES('Meadowlands');
INSERT INTO suburb (suburb) VALUES('Mellons Bay');
INSERT INTO suburb (suburb) VALUES('Middlemore');
INSERT INTO suburb (suburb) VALUES('Murphys Heights');
INSERT INTO suburb (suburb) VALUES('North Park');
INSERT INTO suburb (suburb) VALUES('Orere Point');
INSERT INTO suburb (suburb) VALUES('Otara');
INSERT INTO suburb (suburb) VALUES('Pakuranga');
INSERT INTO suburb (suburb) VALUES('Papatoetoe');
INSERT INTO suburb (suburb) VALUES('Porchester Park');
INSERT INTO suburb (suburb) VALUES('Puhinui');
INSERT INTO suburb (suburb) VALUES('Randwick Park');
INSERT INTO suburb (suburb) VALUES('Redoubt Park');
INSERT INTO suburb (suburb) VALUES('Richmond Park');
INSERT INTO suburb (suburb) VALUES('Settlers Cove');
INSERT INTO suburb (suburb) VALUES('Shelly Park');
INSERT INTO suburb (suburb) VALUES('Silkwood Heights');
INSERT INTO suburb (suburb) VALUES('Sommerville');
INSERT INTO suburb (suburb) VALUES('The Gardens');
INSERT INTO suburb (suburb) VALUES('Totara Heights');
INSERT INTO suburb (suburb) VALUES('Tuscany Estate');
INSERT INTO suburb (suburb) VALUES('Waimahia Landing');
INSERT INTO suburb (suburb) VALUES('Wattle Cove');
INSERT INTO suburb (suburb) VALUES('Wattle Downs');
INSERT INTO suburb (suburb) VALUES('Weymouth');
INSERT INTO suburb (suburb) VALUES('Whitford');
INSERT INTO suburb (suburb) VALUES('Wiri');
INSERT INTO suburb (suburb) VALUES('Papakura');
INSERT INTO suburb (suburb) VALUES('Alfriston');
INSERT INTO suburb (suburb) VALUES('Ardmore');
INSERT INTO suburb (suburb) VALUES('Conifer Grove');
INSERT INTO suburb (suburb) VALUES('Longford Park');
INSERT INTO suburb (suburb) VALUES('Manurewa East');
INSERT INTO suburb (suburb) VALUES('Pahurehure');
INSERT INTO suburb (suburb) VALUES('Opaheke');
INSERT INTO suburb (suburb) VALUES('Red Hill');
INSERT INTO suburb (suburb) VALUES('Rosehill');
INSERT INTO suburb (suburb) VALUES('Takanini');
INSERT INTO suburb (suburb) VALUES('Waitakere City');
INSERT INTO suburb (suburb) VALUES('Glen Eden');
INSERT INTO suburb (suburb) VALUES('Glendene');
INSERT INTO suburb (suburb) VALUES('Green Bay');
INSERT INTO suburb (suburb) VALUES('Henderson');
INSERT INTO suburb (suburb) VALUES('Hobsonville');
INSERT INTO suburb (suburb) VALUES('Kelston');
INSERT INTO suburb (suburb) VALUES('Konini');
INSERT INTO suburb (suburb) VALUES('Laingholm');
INSERT INTO suburb (suburb) VALUES('Massey');
INSERT INTO suburb (suburb) VALUES('New Lynn');
INSERT INTO suburb (suburb) VALUES('Oratia');
INSERT INTO suburb (suburb) VALUES('Piha');
INSERT INTO suburb (suburb) VALUES('Ranui');
INSERT INTO suburb (suburb) VALUES('Sunnyvale');
INSERT INTO suburb (suburb) VALUES('Swanson');
INSERT INTO suburb (suburb) VALUES('Te Atatu');
INSERT INTO suburb (suburb) VALUES('Titirangi');
INSERT INTO suburb (suburb) VALUES('Waiatarua');
INSERT INTO suburb (suburb) VALUES('Waitakere');
INSERT INTO suburb (suburb) VALUES('Western Heights');
INSERT INTO suburb (suburb) VALUES('West Harbour');
INSERT INTO suburb (suburb) VALUES('Whenuapai');
INSERT INTO suburb (suburb) VALUES('Rodney');
INSERT INTO suburb (suburb) VALUES('Gulf Harbour');
INSERT INTO suburb (suburb) VALUES('Manly');
INSERT INTO suburb (suburb) VALUES('Orewa');
INSERT INTO suburb (suburb) VALUES('Red Beach');
INSERT INTO suburb (suburb) VALUES('Sandspit');
INSERT INTO suburb (suburb) VALUES('Silverdale');
INSERT INTO suburb (suburb) VALUES('Stanmore Bay');
INSERT INTO suburb (suburb) VALUES('Waimauku');
INSERT INTO suburb (suburb) VALUES('Waiwera');
INSERT INTO suburb (suburb) VALUES('Warkworth');
INSERT INTO suburb (suburb) VALUES('Whangaparaoa');